### ISSUE TITLE
Information missing from Nextcloud App description

### ISSUE THREAD

**Issue by sunjam** [soudis/discoursesso#1]
[Hey, the Resources tab is missing any information, including the link to this Github page.](https://apps.nextcloud.com/apps/discoursesso)

**Comment by poVoq** [comment]
An update to NC13 would be nice as well, thanks!

**Comment by sunjam** [comment]
Please open a different issue @soudis

**Comment by soudis** [comment]
NC13 support is done, I also updated the app description, but somehow it did not update the info in the app store. I will need to investigate that further

**Comment by sunjam** [comment]
Description on the app store is solid.  Closed.  Thanks!
