### ISSUE TITLE
Nextcloud integrity check fails

### ISSUE THREAD

**Issue by tgressly** [soudis/discoursesso#10]
I am using Nextcloud 17.0.2 with Discourse SSO App 0.9.17 and the integrity check gives me the following errors:

```
discoursesso
	- FILE_MISSING
           <list of files>
        - EXTRA_FILE
           <list of files>
	- INVALID_HASH
           <list of files>
```

**Comment by soudis** [comment]
thanks for bringing this up, I made a mistake when publishing 0.9.17, just released 0.9.18 which should pass the integrity check
