### ISSUE TITLE
Support for Nextcloud 19

### ISSUE THREAD

**Issue by tim-krieger** [soudis/discoursesso#14]
Thank you for this great plugin!

Could you please upgrade discourse sso to support Nextcloud 19?

**Comment by w1n5l0w** [comment]
@soudis Can you tell us if you can adjust the app to NC19 (and NC20) soon? Or how we can help?

**Comment by Patrick-Gasch** [comment]
Top Plugin!
Could you please upgrade discourse sso to support Nextcloud 19?

**Comment by ChristianHaake** [comment]
Hi there! 
Thanks a lot for your great work! 
Do you plan to "update" your plugin to NC19 and/or 20?

**Comment by soudis** [comment]
sorry for the long delay, I always update when we update our servers here. Did it today, unfortunately the App Store is down right now, but I could push the new release before it went byebye, so as soon as it's up version NC19 is out.

NC20 will follow soon, maybe 1-2 month (probably when 20.0.1 is out)

**Comment by kevinkk525** [comment]
I just tested it with NC20 and it worked just fine :-) (ok the groups don't seem to get synchronized.. but probably because some groups have spaces in it. but login works)

**Comment by ChristianHaake** [comment]
Thanks a lot!

**Comment by derspotter** [comment]
Hi, are there any news on when NC20 will be officially supported? Thanks a lot!

**Comment by derspotter** [comment]
When I use the SSO i don't get redirected to Discourse again. I just get stuck at nextcloud. When I type in the url again it redirects me directly to nextcloud and I cant access my forum at all.
edit: sorry for the hassle. Had a typo in the config -.-

**Comment by soudis** [comment]
@derspotter please open another issue and describe your setup and configuration

**Comment by sunjam** [comment]
Nextcloud 21 and PHP 8 are now being released

**Comment by Thatoo** [comment]
@tim-krieger, could you close this issue as support has been provided up to NC 28?
