### ISSUE TITLE
[Feature Request] Shorten group names that are too long

### ISSUE THREAD

**Issue by kevinkk525** [soudis/discoursesso#16]
Problem: I have a rather long group name e.g. "free_candy_crush_game". Groupd synchronization doesn't work on this because discourse doesn't let me create a group with such a long name.

Suggestion: Shorten group names that are longer than what discourse allows, so these groups can be synchronized too. If possible also give the option to shorten from the start or the end. Eg free_candy_crush_game" -> "crush_game"

**Comment by soudis** [comment]
hi kevin, Unfortunately I don't have the time to implement specific requests like this, wouldn't it be an option to just shorten the group names in nextcloud?

**Comment by kevinkk525** [comment]
Hi, thanks a lot for your answer, I understand.
There is no feature in nextcloud to rename a group, so it's not easily possible. I guess the easier workaround would be to create a new group that is just a shortened version for sync with discourse.
