### ISSUE TITLE
Issue with Nextcloud 20?

### ISSUE THREAD

**Issue by alexanderharm** [soudis/discoursesso#17]
After logging in, I get redirected to Nextcloud, where I log in. However, I'm not redirected back to Discourse. Also when manually opening Discourse it keeps redirecting to Nextcloud. Any idea?

**Comment by soudis** [comment]
please provide your config and maybe also track the redirects with your browser (inspect mode -> network monitor).

**Comment by soudis** [comment]
and the app is currently not tested with nextcloud 20, so it may or may not work (i don't know), I will test and upgrade with the next 1-2 month

**Comment by alexanderharm** [comment]
Sorry, my bad. Small typo. Everything works as expected. Thanks a lot for this plugin.

Different question: would you mind if I build a similar plugin for admidio? It is an open source membership management software used by many small profit organisations...

**Comment by soudis** [comment]
super! 

Of course not, feel free to fork it. If you improve things that would also help with this plugin, plz let me know, so I could "steal" back ;)
