### ISSUE TITLE
Get title from LDAP

### ISSUE THREAD

**Issue by ClundXIII** [soudis/discoursesso#21]
Hello,

do you think it would be possible to pass the title from an LDAP connection to Discourse?

**Comment by soudis** [comment]
Hi! Yes, I use that in my setup, but it is a littel messy. The workaround works like this:

First: In Nextcloud LDAP Settings under "Advanced" => "Directory Settings" => "2nd Username field" put in the LDAP attribute you want to use for a title

The the user display name in Nextcloud will be "<LDAP display name> (<LDAP title attribute>)", e.g. "John Doe (Title)"

Then: Configure the discoursesso plugin to extract the title for discourse from the nextcloud user name. It's a rather complicated looking regular expression: "/\(([^\)]*)\)/". Put this in the "Extract title" field for the discoursesso plugin configuration.

Please note that I use the German version of Nextcloud, so the englisch labels for the LDAP configuration fields may differ a littel bit. 

Hope that works for you!

**Comment by ClundXIII** [comment]
Hi,

it works perfectly, thank you :)
