### ISSUE TITLE
Not working since last update

### ISSUE THREAD

**Issue by derspotter** [soudis/discoursesso#25]
Hi, many thinks for this awesome plugin! As of late I get an internal server error, when Im trying to connect via the NC SSO. It seems like it is getting null where it should get an array. This is the logs: 
[PHP] Error: preg_match_all(): No ending delimiter ''' found at /var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php#50

GET /index.php/apps/discoursesso?sso=bm9uY2U9MGM1OTIyZDVjOTEzNDQ1NzY1MWUzMmQ0MmNlOWE0OTgmcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZmb3J1bS5hZGgud29ybGQlMkZzZXNzaW9uJTJGc3NvX2xvZ2lu&sig=6532d124f643ad90bb37f1e1f722b1f553dda46643be1d7ec593c089228a40b2
from 185.66.195.66 by der_spotter at 2021-09-21T20:36:14+00:00

{"reqId":"0Ty0B69CX0aUVzmvvOBS","level":3,"time":"2021-09-21T20:36:14+00:00","remoteAddr":"185.66.195.66","user":"der_spotter","app":"PHP","method":"GET","url":"/index.php/apps/discoursesso?sso=bm9uY2U9MGM1OTIyZDVjOTEzNDQ1NzY1MWUzMmQ0MmNlOWE0OTgmcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZmb3J1bS5hZGgud29ybGQlMkZzZXNzaW9uJTJGc3NvX2xvZ2lu&sig=6532d124f643ad90bb37f1e1f722b1f553dda46643be1d7ec593c089228a40b2","message":"preg_match_all(): No ending delimiter ''' found at /var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php#50","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"22.1.1.2","exception":{"Exception":"Error","Message":"preg_match_all(): No ending delimiter ''' found at /var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php#50","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"preg_match_all(): No ending delimiter ''' found","/var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php",50]},{"file":"/var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php","line":50,"function":"preg_match_all","args":["'/\\'","der_spotter",null]},{"file":"/var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php","line":145,"function":"removeTitleInDisplayName","class":"OCA\\DiscourseSSO\\Controller\\DiscourseController","type":"->","args":["der_spotter"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"sso","class":"OCA\\DiscourseSSO\\Controller\\DiscourseController","type":"->","args":["bm9uY2U9MGM1OTIyZDVjOTEzNDQ1NzY1MWUzMmQ0MmNlOWE0OTgmcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZmb3J1bS5hZGgud29ybGQlMkZzZXNzaW9uJTJGc3NvX2xvZ2lu","6532d124f643ad90bb37f1e1f722b1f553dda46643be1d7ec593c089228a40b2"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DiscourseSSO\\Controller\\DiscourseController"},"sso"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DiscourseSSO\\Controller\\DiscourseController"},"sso"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DiscourseSSO\\Controller\\DiscourseController","sso",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"discoursesso.discourse.sso"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/discoursesso"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"614a423e5158d"}

[index] Error: end(): Argument #1 ($array) must be of type array, null given

GET /index.php/apps/discoursesso?sso=bm9uY2U9MGM1OTIyZDVjOTEzNDQ1NzY1MWUzMmQ0MmNlOWE0OTgmcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZmb3J1bS5hZGgud29ybGQlMkZzZXNzaW9uJTJGc3NvX2xvZ2lu&sig=6532d124f643ad90bb37f1e1f722b1f553dda46643be1d7ec593c089228a40b2
from 185.66.195.66 by der_spotter at 2021-09-21T20:36:14+00:00

{"reqId":"0Ty0B69CX0aUVzmvvOBS","level":3,"time":"2021-09-21T20:36:14+00:00","remoteAddr":"185.66.195.66","user":"der_spotter","app":"index","method":"GET","url":"/index.php/apps/discoursesso?sso=bm9uY2U9MGM1OTIyZDVjOTEzNDQ1NzY1MWUzMmQ0MmNlOWE0OTgmcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZmb3J1bS5hZGgud29ybGQlMkZzZXNzaW9uJTJGc3NvX2xvZ2lu&sig=6532d124f643ad90bb37f1e1f722b1f553dda46643be1d7ec593c089228a40b2","message":"end(): Argument #1 ($array) must be of type array, null given","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"22.1.1.2","exception":{"Exception":"Exception","Message":"end(): Argument #1 ($array) must be of type array, null given","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DiscourseSSO\\Controller\\DiscourseController"},"sso"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DiscourseSSO\\Controller\\DiscourseController","sso",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"discoursesso.discourse.sso"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/discoursesso"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"end(): Argument #1 ($array) must be of type array, null given","Code":0,"Trace":[{"file":"/var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php","line":51,"function":"end","args":[null]},{"file":"/var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php","line":145,"function":"removeTitleInDisplayName","class":"OCA\\DiscourseSSO\\Controller\\DiscourseController","type":"->","args":["der_spotter"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"sso","class":"OCA\\DiscourseSSO\\Controller\\DiscourseController","type":"->","args":["bm9uY2U9MGM1OTIyZDVjOTEzNDQ1NzY1MWUzMmQ0MmNlOWE0OTgmcmV0dXJuX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZmb3J1bS5hZGgud29ybGQlMkZzZXNzaW9uJTJGc3NvX2xvZ2lu","6532d124f643ad90bb37f1e1f722b1f553dda46643be1d7ec593c089228a40b2"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DiscourseSSO\\Controller\\DiscourseController"},"sso"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DiscourseSSO\\Controller\\DiscourseController"},"sso"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DiscourseSSO\\Controller\\DiscourseController","sso",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"discoursesso.discourse.sso"}]},{"file":"/var/www/html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/discoursesso"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/discoursesso/lib/Controller/DiscourseController.php","Line":51},"CustomMessage":"--"},"id":"614a423e5153b"}

**Comment by soudis** [comment]
Hey!

The piece of code is a function to removes the title from the nextcloud username before passing it to discourse. So you either put in an invalid regexp in the "Extract title" setting of the plugin or den username has some weird characters inside. Can you check both and provide the 2 strings?

Thx!

**Comment by derspotter** [comment]
Thank you for the fast answer.
The string of the username is `der_spotter`. It can also be found in the log. But it happens to all users. 
The extract title setting in the plugin says: `'/\'`

**Comment by soudis** [comment]
thx, can you try to remove the "Extraxt title" setting string entirely. Because it is a malformed regexp.

**Comment by derspotter** [comment]
That did the trick! Thank you so much :)
