### ISSUE TITLE
Any plan to update it to Nextcloud 23?

### ISSUE THREAD

**Issue by wokawoka** [soudis/discoursesso#27]
@soudis
Thank you so much for this nextcloud app, our group replies on it on a daily basis!
Do you by chance plan to update it to run on nextcloud 23?
[here](https://github.com/soudis/discoursesso/issues/14#issuecomment-705804394) I've read that you normally update it when you upgrade your servers. 
So here we're crossing our fingers hoping that you are still maintaining it.
Thank you again!

**Comment by soudis** [comment]
Nice to hear, that the app is used :) im still maintaining, however it will take 2‐3 weeks until i will be able to post the updated version

**Comment by wokawoka** [comment]
> Nice to hear, that the app is used :) im still maintaining, however it will take 2‐3 weeks until i will be able to post the updated version

That's really great news! 2-3 weeks still sounds fantastic.
Thank you very much for your work!


P.s.: don´t feel pressured but, since thanks to your plugin our instance has turned overtime into a very deep integration between nextcloud and discourse and our users are using both tools, the future of our small community also depends on you. We keep our fingers crossed :P

**Comment by Ramblurr** [comment]
Just wanted to come by and also express our (a european street brass [band](https://streetnoise.at)) gratitude for maintaining this plugin :heart:  We've totally replaced Google+Dropbox services with our combo of Nextcloud and Discourse.

FYI We're on NC 23 and force-enabled the app, and it seems to be working. I would necessarily recommend this, but I upgraded NC before checking app compatibility :(

**Comment by wokawoka** [comment]
> We're on NC 23 and force-enabled the app, and it seems to be working. I would necessarily recommend this, but I upgraded NC before checking app compatibility :(

Thank you so much for the information! We were waiting for the update but we now might try to test NC23 with the actual version of the app. Thanks

**Comment by soudis** [comment]
sorry for the long delay, the version for NC23 is now available. NC24 will follow soon

**Comment by wokawoka** [comment]
great news. Thank you so much!

**Comment by ptmix** [comment]
Thanks so much for this app.... I am using it. In fact it is the only reason i have not updated from Nextcloud 24 to 25 yet.
Is there any chance we will see a Discourse sso app for v25 in the near future?

**Comment by LostinSpacetime** [comment]
App is working perfectly on NC 25

**Comment by soudis** [comment]
I usually update when I update my nc instances which will be within the next weeks

@LostinSpacetime thx for letting us know it works with nc25 :)! 

Usually the app does not break with nc updates as it uses rather few nc api calls

**Comment by ptmix** [comment]
Thanks for letting me know it works perfectly for you @LostinSpacetime
It did not work perfectly for me (I did have to force install it of course). Besides i prefer supported without "you are own your own" methods in general. What happened here was that asap i did a manual logout from my Discourse instance it did not log in again. Might be some other issues that was my case. Nextcloud 25 gave me some issues i understand is common. Like themes was a bit messed up. I guess when i do a production update i can tweak things back to onormal.

@soudis Thanks for this update. I really appreciate your effort. Discourse SSO truly is a great app.

**Comment by Thatoo** [comment]
@wokawoka, could you close your issue as support has been provided up to NC 28?

**Comment by wokawoka** [comment]
sure, thanks again to @soudis
