### ISSUE TITLE
Support for Nextcloud 24

### ISSUE THREAD

**Issue by LostinSpacetime** [soudis/discoursesso#29]
The app is not listed to support Nextcloud 23 or 24, but on NC23 one can manually activate it, and it works. This app is essential for our team and I don't want to risk, not being able to use it. Did anyone test it with NC 24?

**Comment by p-bo** [comment]
Just in case it wasn't noticed - Nextcloud improved policy regarding changes in core to ease app developers in maintaining compatibility with newer Nextcloud versions:

https://help.nextcloud.com/t/new-process-for-documenting-core-code-changes-that-affect-app-developers/149828?u=p-bo

**Comment by Thatoo** [comment]
@LostinSpacetime, could you close your issue as support has been provided up to NC 28?
