### ISSUE TITLE
 Support for Nextcloud 29 and 30 

### ISSUE THREAD

**Issue by Thatoo** [soudis/discoursesso#36]
Any chance for supporting NC 29 and 30 soon :)?
Would be awesome to upgrade to benefit from performance upgrades.
Thanks for your great work! Appreciating this plugin very much.

**Comment by Thatoo** [comment]
I have done [a PR for 29](https://github.com/soudis/discoursesso/pull/34) but you might want to make one directly for 30. I don't dare to make it because you didn't check my PR for 29 so I guess you prefer to do it by yourself and I understand that.

**Comment by soudis** [comment]
I just uploaded version 1.30.0 for up to NC 30
