### ISSUE TITLE
Users with spaces in their user names are unable to login

### ISSUE THREAD

**Issue by sabberworm** [soudis/discoursesso#5]
It seems discourse has some restrictions on what a user name is. If a nextcloud user does not conform to these, the SSO login fails and I get the following error in discourse:

<img width="605" alt="Login Error. There is a problem with your account. Please contact the site's administrator." src="https://user-images.githubusercontent.com/47652/48274590-f0481e00-e443-11e8-9297-cdf349575a4f.png">

It would be cool if the SSO app could normalize the user name (whilst remaining unique, of course) so that the login would still work.

**Comment by soudis** [comment]
would it be sufficient to replace spaces with underscore "_" characters?

**Comment by sabberworm** [comment]
> would it be sufficient to replace spaces with underscore "_" characters?

If no other user exists with that name, then yes…

**Comment by soudis** [comment]
I just uploaded an new version of the plugin including the feature. You can now set your own replacement string for whitespaces. Hope that's sufficient for now. 

I have not implemented a check if that user name already exists, as my time resources are very limited currently. If you come up with a pull request, I can include it in the next release.

**Comment by sabberworm** [comment]
Great, thanks a lot. I think we can close this.
