### ISSUE TITLE
Nextcloud 17 support

### ISSUE THREAD

**Issue by vranki** [soudis/discoursesso#8]
I'm setting up a new Nextcloud instance and I'd like to use this plugin to integrate with Discourse. 
Latest Nextcloud is 17 but the plugin reports to be compatible with up to 16.

Does the plugin work with version 17 or should I install 16?

**Comment by soudis** [comment]
I will upgrade the app when nextlcoud version 17 hits the stable channel. If you want to use the app now, I would suggest to install version 16 and upgrade when the app is updated too.

**Comment by Ramblurr** [comment]
Nextcloud 17 is now in the stable channel.

**Comment by vranki** [comment]
This would be great to have. I'm trying to integrate NC and Discourse with LDAP server now, but it's painful (you need self-registration page etc) and Discourse LDAP seems to be broken.

This plugin would solve the issue.

**Comment by soudis** [comment]
Updated app to Nextcloud 17 and uploaded to app store

@vranki I also use nextcloud with LDAP backend and discourse authentication via nextcloud using this app and it works quite well. You need an additional user registration tool however to create the users in LDAP. I use a customized self-written NodeJS app, which is unfortunately not usable by other setups.

**Comment by vranki** [comment]
Installed on Nextcloud 17 successfully (i think). Thanks.
